from __future__ import annotations

from typing import Protocol

from smt_os.domain.assignments.entities import GroupAssignment, GroupSlot, MealAssignment, MealSlot
from smt_os.domain.checkins.entities import Checkin
from smt_os.domain.common.enums import CheckinType
from smt_os.domain.events.entities import Event
from smt_os.domain.forms.entities import FormField, RegistrationForm
from smt_os.domain.participants.entities import Participant, Registration, Ticket
from smt_os.domain.surveys.entities import SurveyQuestion, SurveyResponse
from smt_os.domain.team.entities import ActionItem, Meeting, MeetingNote, TeamDocument


class EventRepository(Protocol):
    def save(self, event: Event) -> None: ...

    def get(self, event_id: str) -> Event | None: ...

    def get_by_slug(self, slug: str) -> Event | None: ...

    def list(self) -> list[Event]: ...

    def delete(self, event_id: str) -> Event | None: ...


class RegistrationRepository(Protocol):
    def save(self, registration: Registration) -> None: ...


class ParticipantRepository(Protocol):
    def save(self, participant: Participant) -> None: ...

    def get(self, participant_id: str) -> Participant | None: ...

    def list_by_event(
        self,
        event_id: str,
        church_or_school: str | None = None,
        grade: str | None = None,
        name_query: str | None = None,
    ) -> list[Participant]: ...


class TicketRepository(Protocol):
    def save(self, ticket: Ticket) -> None: ...

    def find_by_token(self, token: str) -> Ticket | None: ...

    def find_by_participant_id(self, participant_id: str) -> Ticket | None: ...


class CheckinRepository(Protocol):
    def save(self, checkin: Checkin) -> None: ...

    def exists(self, event_id: str, participant_id: str, checkin_type: CheckinType) -> bool: ...

    def count_for_participants(
        self,
        event_id: str,
        participant_ids: set[str],
        checkin_type: CheckinType,
    ) -> int: ...


class RegistrationFormRepository(Protocol):
    def save(self, form: RegistrationForm) -> None: ...

    def get_active(self, event_id: str) -> RegistrationForm | None: ...

    def replace_fields(self, form_id: str, fields: list[FormField]) -> None: ...

    def list_fields(self, form_id: str) -> list[FormField]: ...


class AssignmentRepository(Protocol):
    def replace_meal_slots(self, event_id: str, slots: list[MealSlot]) -> None: ...

    def list_meal_slots(self, event_id: str) -> list[MealSlot]: ...

    def replace_meal_assignments(self, event_id: str, items: list[MealAssignment]) -> None: ...

    def list_meal_assignments(self, event_id: str) -> list[MealAssignment]: ...

    def replace_group_slots(self, event_id: str, groups: list[GroupSlot]) -> None: ...

    def list_group_slots(self, event_id: str) -> list[GroupSlot]: ...

    def replace_group_assignments(self, event_id: str, items: list[GroupAssignment]) -> None: ...

    def list_group_assignments(self, event_id: str) -> list[GroupAssignment]: ...


class SurveyRepository(Protocol):
    def replace_questions(self, event_id: str, questions: list[SurveyQuestion]) -> None: ...

    def list_questions(self, event_id: str) -> list[SurveyQuestion]: ...

    def save_response(self, response: SurveyResponse) -> None: ...

    def list_responses(self, event_id: str) -> list[SurveyResponse]: ...


class TeamRepository(Protocol):
    def save_meeting(self, meeting: Meeting) -> None: ...

    def list_meetings(self, org_id: str) -> list[Meeting]: ...

    def save_meeting_note(self, note: MeetingNote) -> None: ...

    def list_meeting_notes(self, meeting_id: str) -> list[MeetingNote]: ...

    def save_action_item(self, item: ActionItem) -> None: ...

    def list_action_items(self, org_id: str, status: str | None = None) -> list[ActionItem]: ...

    def save_document(self, doc: TeamDocument) -> None: ...

    def list_documents(self, org_id: str, kind: str | None = None) -> list[TeamDocument]: ...
